[WIP] Create file
mdiep/Tentacle pull request #55
Opened 2016-12-22 21:23 UTC by Palleas

I'm starting to work on ways to create files using Tentacle. This is a WIP because I just started and I figured getting feedback as early as possible will probably be best.

* Adding [Ogra](https://github.com/edwardaux/Ogra) to serialize models into JSON
* Creating a protocol for those encodable object, with an associated type for the response, I don't like the name `InputType` tho.

Please let me know what you think so far. 👍

2016-12-22 22:14 UTC, mdiep reviewed
This seems like a fine direction. I'm assuming that most of these types will be `internal` and exposed only as methods on the client.

2016-12-22 22:14 UTC, mdiep commented on Tentacle/Commit.swift
> +    let sha: String
We should make `SHA` a type. It could be a thin wrapper over `String`:

```swift
struct SHA {
    let string: String
}
```

2016-12-22 22:14 UTC, mdiep commented on Tentacle/ResourceType.swift
> +public protocol InputType: Encodable, Hashable {
We could also name it `RequestType`. I don't mind `InputType` though.

2016-12-22 22:14 UTC, mdiep commented on Tentacle/FileResponse.swift
> +    let commit: Commit
If a `Commit` is just a SHA, then this could probably be `let commit: SHA`.

2016-12-23 08:51 UTC, Palleas commented on Tentacle/Commit.swift
> +    let sha: String
There are other stuff but I will add them later 👍

2016-12-23 08:51 UTC, Palleas commented on Tentacle/ResourceType.swift
> +public protocol InputType: Encodable, Hashable {
`RequestType` with a `Response` associated type makes a lot of sense thought 🤔

2016-12-24 11:36 UTC, Palleas commented
@mdiep It's working on my side, let me know what you think!
I didn't use the current Fixture model because creating a file requires credentials so I'm not sure if changing the `update-fixtures` script is worth it. Also it's different when it's a POST/PUT request, once the file has been created you can't really update the fixture file anymore... 🤔

2016-12-24 21:25 UTC, mdiep requested changes

2016-12-24 21:25 UTC, mdiep commented on Tentacle/Client.swift
> +            }
These are a lot of code here that's shared with `fetch`. We should somehow combine or share code between them.

2016-12-24 21:25 UTC, mdiep commented on Tentacle/Commit.swift
> +    public let sha: String
We should really add a `SHA` type for this. (I missed this on the previous PR.)

2016-12-24 21:25 UTC, mdiep commented on Tentacle/Client.swift
> +    internal func send<Request: RequestType>(_ request: Request, to endpoint: Endpoint, method: String) -> SignalProducer<(Response, Request.Response), Error> where Request.Response == Request.Respon
We should add an `enum` for the `method`.

2016-12-24 21:25 UTC, mdiep commented on Tentacle/Client.swift
> +            urlRequest.httpBody = payload
I think the `httpBody` and `httpMethod` could be set inside the `create` method. (It could take a `RequestType` and encode it.)

2016-12-26 09:37 UTC, Palleas commented on Tentacle/Client.swift
> +    internal func send<Request: RequestType>(_ request: Request, to endpoint: Endpoint, method: String) -> SignalProducer<(Response, Request.Response), Error> where Request.Response == Request.Respon
That's something that really makes me wonder in FoundationKit. How come it's not an enum already? 🤔

2016-12-28 23:25 UTC, mdiep commented
Let me know when this is ready for another review. (It's still marked WIP.)

2017-01-05 15:50 UTC, Palleas commented
I think the only remaining thing is merging some code between `fetch` and `send`, I'll tackle that tonight if I can. Sorry for the delay I've been away for a family emergency! 😁

2017-01-06 17:49 UTC, mdiep commented
There's no rush on my end. Please take your time!

2017-01-16 14:08 UTC, Palleas commented
OK I'm officially back home so I'm tackling this tonight (just so you don't worry 😁).

2017-01-17 00:02 UTC, Palleas commented
Rebased and updated! 💃

2017-01-20 14:02 UTC, mdiep requested changes
A few minor changes, but this is looking good API-wise.

It could also use some tests for encoding.

2017-01-20 14:02 UTC, mdiep commented on Tentacle/Client.swift
> +    internal static func create<Request: RequestType>(_ url: URL, _ request: Request, _ credentials: Client.Credentials?, contentType: String? = Client.APIContentType) -> URLRequest {
Can we combine this with the variant above? Make `request` an optional value?

2017-01-20 14:02 UTC, mdiep commented on Tentacle/Client.swift
> +public enum HTTPMethod: String {
Does this need to be `public`? Let's make it `private` or `internal` if possible.

2017-01-24 01:42 UTC, Palleas commented on Tentacle/Client.swift
> +    internal static func create<Request: RequestType>(_ url: URL, _ request: Request, _ credentials: Client.Credentials?, contentType: String? = Client.APIContentType) -> URLRequest {
The problem I have with an optional Request is the compiler not being able to infer the type. Any idea how to avoid that cleanly?

2017-01-24 01:42 UTC, Palleas commented on Tentacle/Client.swift
> +public enum HTTPMethod: String {
Fixed!

2017-01-25 13:55 UTC, mdiep reviewed
This looks good! But it could use some tests for encoding.

2017-01-25 18:12 UTC, Palleas commented
Glad you suggested to add those encoding tests because decoding JSON wasn't working at all 😅

2017-01-26 00:59 UTC, mdiep approved these changes

2017-01-26 01:00 UTC, merged

2017-01-26 01:00 UTC, mdiep commented
🎉

2017-01-26 01:13 UTC, Palleas commented
Well that was fun 🚀